# Generated by Django 2.2.19 on 2024-03-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Линейка')),
            ],
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='tobacco_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixes.Lines'),
        ),
    ]
