# Generated by Django 2.2.19 on 2024-03-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0002_auto_20240304_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='line',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='mixes.Lines'),
            preserve_default=False,
        ),
    ]
