# Generated by Django 2.2.19 on 2024-03-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0003_company_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mixes.Lines'),
        ),
    ]
