# Generated by Django 2.2.19 on 2024-03-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0005_auto_20240305_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lines',
            options={'ordering': ('name',), 'verbose_name': 'Линейка', 'verbose_name_plural': 'Линейки'},
        ),
        migrations.RemoveField(
            model_name='lines',
            name='line',
        ),
        migrations.AddField(
            model_name='lines',
            name='company',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mixes.Company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='flavor',
            field=models.ManyToManyField(db_index=True, related_name='tobacco', to='mixes.Flavor'),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixes.Strength'),
        ),
    ]
