# Generated by Django 2.2.19 on 2024-03-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0007_auto_20240305_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixes.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='flavor',
            field=models.ManyToManyField(db_index=True, related_name='tobacco', to='mixes.Flavor', verbose_name='Аромат'),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixes.Strength', verbose_name='Крепкость'),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='tobacco_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixes.Lines', verbose_name='Линейка'),
        ),
    ]
