# Generated by Django 2.2.19 on 2024-03-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0008_auto_20240305_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mixestobacco',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AddConstraint(
            model_name='tobacco',
            constraint=models.UniqueConstraint(fields=('company', 'tobacco_line', 'name'), name='tobacco_unique'),
        ),
    ]
